#
# This example reads an invoice document using the pre-trained Form Recognizer Invoice service
# Documentation: https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/quickstarts/get-started-with-form-recognizer#analyze-using-a-prebuilt-model-invoices-receipts-ids-
#

##### This request initates the invoice reading

# @name read_invoice
POST {{cognitive_services_endpoint}}/formrecognizer/v2.1/prebuilt/invoice/analyze
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{cognitive_services_key}}

{
    "source": "https://github.com/Azure-Samples/cognitive-services-REST-api-samples/raw/master/curl/form-recognizer/Invoice-6.pdf"
}

##### This request queries the status of the Read API operation

# @name get_results
GET {{read_invoice.response.headers.Operation-Location}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{cognitive_services_key}}